/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as ManagerTeamRouteImport } from './routes/manager.team'
import { Route as ManagerReportsRouteImport } from './routes/manager.reports'
import { Route as ManagerAssignRouteImport } from './routes/manager.assign'
import { Route as EmployeeOngoingRouteImport } from './routes/employee.ongoing'
import { Route as EmployeeCompletedRouteImport } from './routes/employee.completed'
import { Route as EmployeeAssignedRouteImport } from './routes/employee.assigned'
import { Route as EmployeeAddRouteImport } from './routes/employee.add'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManagerRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const ManagerTeamRoute = ManagerTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerReportsRoute = ManagerReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ManagerRoute,
} as any)
const ManagerAssignRoute = ManagerAssignRouteImport.update({
  id: '/assign',
  path: '/assign',
  getParentRoute: () => ManagerRoute,
} as any)
const EmployeeOngoingRoute = EmployeeOngoingRouteImport.update({
  id: '/ongoing',
  path: '/ongoing',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeCompletedRoute = EmployeeCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeAssignedRoute = EmployeeAssignedRouteImport.update({
  id: '/assigned',
  path: '/assigned',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeAddRoute = EmployeeAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => EmployeeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/employee/add': typeof EmployeeAddRoute
  '/employee/assigned': typeof EmployeeAssignedRoute
  '/employee/completed': typeof EmployeeCompletedRoute
  '/employee/ongoing': typeof EmployeeOngoingRoute
  '/manager/assign': typeof ManagerAssignRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/team': typeof ManagerTeamRoute
  '/employee/': typeof EmployeeIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/employee/add': typeof EmployeeAddRoute
  '/employee/assigned': typeof EmployeeAssignedRoute
  '/employee/completed': typeof EmployeeCompletedRoute
  '/employee/ongoing': typeof EmployeeOngoingRoute
  '/manager/assign': typeof ManagerAssignRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/team': typeof ManagerTeamRoute
  '/employee': typeof EmployeeIndexRoute
  '/manager': typeof ManagerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/manager': typeof ManagerRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/employee/add': typeof EmployeeAddRoute
  '/employee/assigned': typeof EmployeeAssignedRoute
  '/employee/completed': typeof EmployeeCompletedRoute
  '/employee/ongoing': typeof EmployeeOngoingRoute
  '/manager/assign': typeof ManagerAssignRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/team': typeof ManagerTeamRoute
  '/employee/': typeof EmployeeIndexRoute
  '/manager/': typeof ManagerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employee'
    | '/manager'
    | '/sitemap.xml'
    | '/employee/add'
    | '/employee/assigned'
    | '/employee/completed'
    | '/employee/ongoing'
    | '/manager/assign'
    | '/manager/reports'
    | '/manager/team'
    | '/employee/'
    | '/manager/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/employee/add'
    | '/employee/assigned'
    | '/employee/completed'
    | '/employee/ongoing'
    | '/manager/assign'
    | '/manager/reports'
    | '/manager/team'
    | '/employee'
    | '/manager'
  id:
    | '__root__'
    | '/'
    | '/employee'
    | '/manager'
    | '/sitemap.xml'
    | '/employee/add'
    | '/employee/assigned'
    | '/employee/completed'
    | '/employee/ongoing'
    | '/manager/assign'
    | '/manager/reports'
    | '/manager/team'
    | '/employee/'
    | '/manager/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeeRoute: typeof EmployeeRouteWithChildren
  ManagerRoute: typeof ManagerRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/manager/team': {
      id: '/manager/team'
      path: '/team'
      fullPath: '/manager/team'
      preLoaderRoute: typeof ManagerTeamRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/reports': {
      id: '/manager/reports'
      path: '/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof ManagerReportsRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/manager/assign': {
      id: '/manager/assign'
      path: '/assign'
      fullPath: '/manager/assign'
      preLoaderRoute: typeof ManagerAssignRouteImport
      parentRoute: typeof ManagerRoute
    }
    '/employee/ongoing': {
      id: '/employee/ongoing'
      path: '/ongoing'
      fullPath: '/employee/ongoing'
      preLoaderRoute: typeof EmployeeOngoingRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/completed': {
      id: '/employee/completed'
      path: '/completed'
      fullPath: '/employee/completed'
      preLoaderRoute: typeof EmployeeCompletedRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/assigned': {
      id: '/employee/assigned'
      path: '/assigned'
      fullPath: '/employee/assigned'
      preLoaderRoute: typeof EmployeeAssignedRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/add': {
      id: '/employee/add'
      path: '/add'
      fullPath: '/employee/add'
      preLoaderRoute: typeof EmployeeAddRouteImport
      parentRoute: typeof EmployeeRoute
    }
  }
}

interface EmployeeRouteChildren {
  EmployeeAddRoute: typeof EmployeeAddRoute
  EmployeeAssignedRoute: typeof EmployeeAssignedRoute
  EmployeeCompletedRoute: typeof EmployeeCompletedRoute
  EmployeeOngoingRoute: typeof EmployeeOngoingRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeAddRoute: EmployeeAddRoute,
  EmployeeAssignedRoute: EmployeeAssignedRoute,
  EmployeeCompletedRoute: EmployeeCompletedRoute,
  EmployeeOngoingRoute: EmployeeOngoingRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

interface ManagerRouteChildren {
  ManagerAssignRoute: typeof ManagerAssignRoute
  ManagerReportsRoute: typeof ManagerReportsRoute
  ManagerTeamRoute: typeof ManagerTeamRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
}

const ManagerRouteChildren: ManagerRouteChildren = {
  ManagerAssignRoute: ManagerAssignRoute,
  ManagerReportsRoute: ManagerReportsRoute,
  ManagerTeamRoute: ManagerTeamRoute,
  ManagerIndexRoute: ManagerIndexRoute,
}

const ManagerRouteWithChildren =
  ManagerRoute._addFileChildren(ManagerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeeRoute: EmployeeRouteWithChildren,
  ManagerRoute: ManagerRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
